/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details take a look at the Writing Custom Plugins chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.8/userguide/custom_plugins.html
 */

plugins {
    // Apply the Java Gradle plugin development plugin to add support for developing Gradle plugins
    `java-gradle-plugin`
}

repositories {
    // Use JCenter for resolving dependencies.
    jcenter()
}

dependencies {
    implementation("com.github.javaparser:javaparser-symbol-solver-core:3.18.0")
}

gradlePlugin {
    // Define the plugin
    val greeting by plugins.creating {
        id = "jaffa-rpc-plugin"
        implementationClass = "com.jaffa.rpc.gradle.plugin.JaffaRpcGradlePluginPlugin"
    }
}